# Generated by Django 2.2 on 2020-12-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(max_length=200)),
                ('judul', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=200)),
                ('katalog_jurusan', models.CharField(max_length=200)),
                ('jumlah_buku', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_artikel', models.CharField(max_length=200)),
                ('judul_terbitan', models.CharField(max_length=200)),
                ('issn', models.IntegerField()),
                ('bahasa', models.CharField(max_length=200)),
                ('tempat_terbit', models.CharField(max_length=200)),
                ('tahun', models.IntegerField(max_length=200)),
                ('volume', models.CharField(max_length=200)),
                ('penerbit', models.CharField(max_length=200)),
                ('frekuensi_penerbitan', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=200)),
                ('abstraksi', models.TextField()),
                ('kata_kunci', models.CharField(max_length=200)),
                ('lokasi', models.CharField(max_length=200)),
                ('terakreditasi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=200)),
                ('abstraksi', models.TextField()),
                ('pembimbing', models.CharField(max_length=200)),
                ('jenis_penulisan', models.CharField(max_length=200)),
                ('lokasi', models.CharField(max_length=200)),
            ],
        ),
    ]
