# Generated by Django 2.2 on 2020-12-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='tahun',
            field=models.IntegerField(),
        ),
    ]
