# Generated by Django 2.2 on 2021-01-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0002_auto_20201231_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='katalog_jurusan',
            field=models.CharField(choices=[('psikologi', 'Psikologi'), ('informatika', 'Informatika'), ('teknik mesin', 'Teknik Mesin'), ('teknik elektro', 'Teknik Elektro'), ('kedokteran', 'Kedokteran'), ('farmasi', 'Farmasi'), ('biologi', 'Biologi'), ('fisika', 'Fisika')], default='psikologi', max_length=200),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='lokasi',
            field=models.CharField(choices=[('semua lokasi', 'Semua Lokasi'), ('perpustakaan ft', 'Perpustakaan FT'), ('perpustakaan fkip', 'Perpustakaan FKIP'), ('perpustakaan fk', 'Perpustakaan FK'), ('perpustakaan fisip', 'Perpustakaan FISIP'), ('perpustakaan ffs', 'Perpustakaan FFS'), ('perpustakaan feb', 'Perpustakaan FEB')], default='semua lokasi', max_length=200),
        ),
    ]
