# Generated by Django 2.2 on 2021-01-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0003_auto_20210103_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='keyword',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
