# Generated by Django 2.2 on 2021-01-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0008_auto_20210114_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='lokasi',
            new_name='lokasi_repository',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='judul',
            new_name='pembimbing_repository',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='pembimbing',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='penulis',
        ),
        migrations.AddField(
            model_name='repository',
            name='judul_repository',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='repository',
            name='keyword_repository',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='penulis_repository',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='repository',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='lokasi',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
