# Generated by Django 2.2 on 2021-01-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0009_auto_20210115_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='judul_repository',
            new_name='judul',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='keyword_repository',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='lokasi_repository',
            new_name='lokasi',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='pembimbing_repository',
            new_name='pembimbing',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='penulis_repository',
            new_name='penulis',
        ),
    ]
