# Generated by Django 2.2 on 2021-02-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0010_auto_20210115_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='katalog_jurusan',
            field=models.CharField(choices=[('psikologi', 'Psikologi'), ('informatika', 'Informatika'), ('teknik mesin', 'Teknik Mesin'), ('teknik elektro', 'Teknik Elektro'), ('kedokteran', 'Kedokteran'), ('farmasi', 'Farmasi'), ('biologi', 'Biologi'), ('fisika', 'Fisika'), ('ekonomi', 'Ekonomi'), ('akuntansi', 'Akuntansi'), ('pendidikan guru sekolah daser', 'Pendidikan Guru Sekolah Dasar'), ('sastra indonesia', 'Sasta Indonesia'), ('sastra inggris', 'Sastra Inggris'), ('ilmu politik', 'Ilmu Politik')], default='psikologi', max_length=200),
        ),
        migrations.AlterField(
            model_name='journal',
            name='bahasa',
            field=models.CharField(choices=[('indonesia', 'Indonesia'), ('english', 'English')], max_length=200),
        ),
        migrations.AlterField(
            model_name='journal',
            name='lokasi',
            field=models.CharField(blank=True, choices=[('semua lokasi', 'Semua Lokasi'), ('perpustakaan ft', 'Perpustakaan FT'), ('perpustakaan fkip', 'Perpustakaan FKIP'), ('perpustakaan fk', 'Perpustakaan FK'), ('perpustakaan fisip', 'Perpustakaan FISIP'), ('perpustakaan ffs', 'Perpustakaan FFS'), ('perpustakaan feb', 'Perpustakaan FEB')], default='semua lokasi', max_length=200),
        ),
    ]
