# Generated by Django 2.2 on 2021-02-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0011_auto_20210203_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='bahasa',
            field=models.CharField(choices=[('indonesia', 'Indonesia'), ('english', 'English')], default='indonesia', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='bahasa',
            field=models.CharField(choices=[('indonesia', 'Indonesia'), ('english', 'English')], default='indonesia', max_length=200),
        ),
    ]
