# Generated by Django 2.2 on 2021-02-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0013_auto_20210206_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='judul',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='keyword',
            field=models.TextField(blank=True, null=True),
        ),
    ]
