# Generated by Django 2.2 on 2021-02-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0015_auto_20210206_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='judul',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
