# Generated by Django 2.2 on 2021-02-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0016_auto_20210206_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='judul',
            field=models.TextField(blank=True),
        ),
    ]
