# Generated by Django 2.2 on 2021-02-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0018_auto_20210206_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='judul',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='keyword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='judul_artikel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='journal',
            name='judul_terbitan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='journal',
            name='kata_kunci',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='journal',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='repository',
            name='keyword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
